const byId=id=>document.getElementById(id);
const norm=value=>(value%360+360)%360;
const polar=(degree,radius)=>[200+Math.sin(degree*Math.PI/180)*radius,200-Math.cos(degree*Math.PI/180)*radius];
const point=(degree,radius)=>polar(degree,radius).map(value=>value.toFixed(2));
const liveColors={wood:'#93e3ad',fire:'#ffab95',earth:'#f4cf83',metal:'#d7e1eb',water:'#b7dcf3'};
const liveColor=symbol=>liveColors[symbolElements[symbol]]||'#fff';
const cardinalNames=['北','东北','东','东南','南','西南','西','西北'];
let cameraStream=null,sensorActive=false,sensorHeading=null,manualHeading=0,calibrationOffset=0,scene='indoor',sensorTimer=null;
function setStatus(message){byId('liveStatus').textContent=message;}
function currentHeading(){return norm(sensorActive&&sensorHeading!==null?sensorHeading+calibrationOffset:manualHeading);}
function renderHeading(){const heading=currentHeading();byId('liveDial').setAttribute('transform',`rotate(${-heading} 200 200)`);byId('headingValue').textContent=`${Math.round(heading)}°`;byId('headingDirection').textContent=cardinalNames[Math.round(heading/45)%8];byId('headingState').textContent=sensorActive?'方向感应已开启':'手动校准方位';byId('sourceChip').textContent=sensorActive?'方向感应':'手动方位';byId('angleOutput').textContent=`${sensorActive&&calibrationOffset>0?'+':''}${sensorActive?calibrationOffset:manualHeading}°`;}
function buildCompass(){const ticks=Array.from({length:72},(_,i)=>{const degree=i*5,a=point(degree,i%3===0?166:170),b=point(degree,177);return `<line class="tick${i%3===0?' major':''}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`;}).join('');const degreeLabels=Array.from({length:12},(_,i)=>{const degree=i*30,[x,y]=point(degree,153);return `<text class="degree" x="${x}" y="${y}">${degree}</text>`;}).join('');const mountainLabels=mountains.map((name,i)=>{const [x,y]=point(i*15,133);return `<text class="mountain" x="${x}" y="${y}" fill="${liveColor(name)}">${name}</text>`;}).join('');const cardinals=['北','东','南','西'].map((name,i)=>{const [x,y]=point(i*90,100);return `<text class="cardinal${i===0?' north':''}" x="${x}" y="${y}">${name}</text>`;}).join('');byId('liveCompass').innerHTML=`<g id="liveDial" class="dial"><circle class="ring-face" cx="200" cy="200" r="182"/><circle class="ring-line" cx="200" cy="200" r="160"/><circle class="ring-line inner-ring" cx="200" cy="200" r="116"/><circle class="ring-line" cx="200" cy="200" r="76"/>${ticks}${degreeLabels}${mountainLabels}${cardinals}<path d="M200 10l-7 14h14z" fill="#ef725f"/></g>`;renderHeading();}
function setScene(next){scene=next;for(const [name,id] of [['indoor','indoorScene'],['outdoor','outdoorScene']]){const active=name===next;byId(id).classList.toggle('selected',active);byId(id).setAttribute('aria-pressed',String(active));}byId('sceneChip').textContent=next==='indoor'?'室内实景':'室外实景';const url=new URL(location.href);url.searchParams.set('scene',next);history.replaceState(null,'',url);}
function stopCamera(){if(cameraStream){for(const track of cameraStream.getTracks())track.stop();cameraStream=null;}const video=byId('cameraView');video.pause();video.srcObject=null;video.hidden=true;byId('cameraPlaceholder').hidden=false;byId('cameraState').textContent='相机未开启';byId('startCamera').hidden=false;byId('stopCamera').hidden=true;}
async function startCamera(){if(cameraStream)return;if(!navigator.mediaDevices?.getUserMedia){setStatus('当前浏览器无法开启相机，请在手机浏览器的 HTTPS 页面使用。');return;}byId('startCamera').disabled=true;setStatus('正在开启相机…');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(document.hidden){stream.getTracks().forEach(track=>track.stop());return;}cameraStream=stream;const video=byId('cameraView');video.srcObject=stream;await video.play();if(document.hidden||cameraStream!==stream){stream.getTracks().forEach(track=>track.stop());return;}video.hidden=false;byId('cameraPlaceholder').hidden=true;byId('cameraState').textContent='相机已开启';byId('startCamera').hidden=true;byId('stopCamera').hidden=false;stream.getVideoTracks()[0]?.addEventListener('ended',()=>{stopCamera();setStatus('相机已关闭。')},{once:true});setStatus('相机已开启；画面仅在本机显示。');}catch(error){stopCamera();const message=error.name==='NotAllowedError'?'相机权限未开启，请在浏览器设置中允许访问相机。':error.name==='NotFoundError'?'未检测到可用相机。':'相机暂时无法使用，请关闭其他占用相机的应用后重试。';setStatus(message);}finally{byId('startCamera').disabled=false;}}
function stopSensor(){clearTimeout(sensorTimer);window.removeEventListener('deviceorientation',onOrientation);window.removeEventListener('deviceorientationabsolute',onOrientation);if(sensorActive){manualHeading=Math.round(currentHeading());sensorActive=false;sensorHeading=null;calibrationOffset=0;const input=byId('manualAngle');input.min='0';input.max='359';input.value=String(manualHeading);byId('angleLabel').textContent='手动朝向';renderHeading();}}
function onOrientation(event){let heading=null;if(Number.isFinite(event.webkitCompassHeading))heading=event.webkitCompassHeading;else if(event.absolute&&Number.isFinite(event.alpha))heading=norm(360-event.alpha+(screen.orientation?.angle||0));if(heading===null)return;clearTimeout(sensorTimer);if(!sensorActive){sensorActive=true;calibrationOffset=0;const input=byId('manualAngle');input.min='-180';input.max='180';input.value='0';byId('angleLabel').textContent='校准偏移';setStatus('已收到绝对方向数据；可用滑杆修正磁场偏差。');}sensorHeading=heading;renderHeading();}
async function startSensor(){if(!window.DeviceOrientationEvent){setStatus('当前浏览器没有方向感应功能，请使用手动朝向。');return;}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted'){setStatus('未获得方向权限，请使用手动朝向。');return;}}if(document.hidden)return;window.addEventListener('deviceorientation',onOrientation);window.addEventListener('deviceorientationabsolute',onOrientation);clearTimeout(sensorTimer);sensorTimer=setTimeout(()=>{if(!sensorActive)setStatus('未收到绝对方向数据，请使用手动朝向。');},3000);setStatus('正在读取方向数据…');}catch{setStatus('方向权限未开启，请使用手动朝向。');}}
byId('indoorScene').onclick=()=>setScene('indoor');byId('outdoorScene').onclick=()=>setScene('outdoor');byId('startCamera').onclick=startCamera;byId('stopCamera').onclick=()=>{stopCamera();setStatus('相机已关闭。');};byId('startSensor').onclick=startSensor;
byId('manualAngle').oninput=event=>{if(sensorActive)calibrationOffset=Number(event.target.value);else manualHeading=Number(event.target.value);renderHeading();};byId('compassSize').oninput=event=>{const size=Number(event.target.value);document.querySelector('.compass-stage').style.setProperty('--compass-scale',size/100);byId('sizeOutput').textContent=`${size}%`;};byId('styleButton').onclick=()=>{const simple=document.querySelector('.compass-stage').classList.toggle('simple');byId('styleButton').setAttribute('aria-pressed',String(simple));byId('styleButton').textContent=simple?'切换为完整罗盘':'切换为简洁罗盘';};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera();stopSensor();}});window.addEventListener('pagehide',()=>{stopCamera();stopSensor();});
buildCompass();setScene(new URLSearchParams(location.search).get('scene')==='outdoor'?'outdoor':'indoor');
