import {api,escapeHtml as esc} from './auth-client.js';
const $=id=>document.getElementById(id),date=ms=>new Date(ms).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
let page=1,query='',tab='users',loading=0;
function error(error){if(error.status===401){location.replace('/login?admin=1');return;}$('adminFeedback').textContent=error.message;$('adminFeedback').hidden=false;}
async function overview(){const data=await api('/api/admin/overview');$('totalUsers').textContent=data.total;$('pendingUsers').textContent=data.pending||0;$('enabledUsers').textContent=data.enabled||0;}
async function loadUsers(){
 const revision=++loading;const data=await api('/api/admin/users?page='+page+'&q='+encodeURIComponent(query));if(revision!==loading)return;
 $('usersList').innerHTML=data.users.length?data.users.map(user=>{
  const label=user.approval==='pending'?'待审核':user.approval==='rejected'?'未通过':user.status==='disabled'?'已停用':'已启用';
  const badge=user.approval==='pending'?'pending':user.status==='disabled'?'disabled':'';
  let actions='';if(user.role!=='admin'){
   if(user.approval==='pending')actions=`<button class="secondary" data-action="reject" data-id="${user.id}">不通过</button><button class="secondary accent" data-action="approve" data-id="${user.id}">审核通过</button>`;
   else if(user.approval==='approved')actions=`<button class="secondary ${user.status==='enabled'?'accent':''}" data-action="${user.status==='enabled'?'disable':'enable'}" data-id="${user.id}">${user.status==='enabled'?'停用账号':'启用账号'}</button>`;
  }
  return `<article class="account-row"><div><div class="row-title"><h3>${esc(user.name)}</h3><span class="badge ${badge}">${label}</span>${user.role==='admin'?'<span class="badge">管理员</span>':''}</div><p>${esc(user.login)}</p><p>创建于 ${date(user.createdAt)}</p></div>${actions?`<div class="row-actions">${actions}</div>`:''}</article>`;
 }).join(''):'<div class="empty">暂无匹配账号</div>';
 $('pageLabel').textContent=`第 ${page} 页 · 共 ${data.total} 个账号`;$('previousPage').disabled=page<=1;$('nextPage').disabled=page*20>=data.total;
}
async function loadInvites(){const {invitations}=await api('/api/admin/invitations');$('invitesList').innerHTML=invitations.length?invitations.map(item=>`<article class="account-row"><div><div class="row-title"><h3>${esc(item.name)}</h3><span class="badge ${item.enabled?'':'disabled'}">${!item.enabled?'已停用':item.expires_at<=Date.now()?'已到期':item.use_count>=item.max_uses?'已用完':'可使用'}</span></div><p>尾号 ${esc(item.hint)} · 已用 ${item.use_count} / ${item.max_uses} 次</p><p>到期时间 ${date(item.expires_at)}</p></div><button class="secondary" data-invite="${item.id}" data-enabled="${!item.enabled}">${item.enabled?'停用':'启用'}</button></article>`).join(''):'<div class="empty">尚未创建邀请码</div>';}
async function loadEvents(){const {events}=await api('/api/admin/events');const names={'account.create':'创建账号','account.approve':'审核通过','account.reject':'审核未通过','account.enable':'启用账号','account.disable':'停用账号','invitation.create':'生成邀请码','invitation.enable':'启用邀请码','invitation.disable':'停用邀请码'};$('eventsList').innerHTML=events.length?events.map(e=>`<article class="account-row event-row"><div>${esc(e.actor||'管理员')} · ${esc(names[e.action]||e.action)}</div><div>${esc(e.target)}</div><time>${date(e.created_at)}</time></article>`).join(''):'<div class="empty">暂无操作记录</div>';}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=async()=>{tab=button.dataset.tab;$('adminFeedback').hidden=true;document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1;});for(const key of ['users','invitations','events'])$(key+'Section').hidden=key!==tab;try{await ({users:loadUsers,invitations:loadInvites,events:loadEvents}[tab])();}catch(e){error(e);}});
$('searchUsers').onsubmit=e=>{e.preventDefault();query=new FormData(e.currentTarget).get('q').trim();page=1;loadUsers().catch(error);};
$('previousPage').onclick=()=>{page--;loadUsers().catch(error);};$('nextPage').onclick=()=>{page++;loadUsers().catch(error);};
$('usersList').onclick=async e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;button.disabled=true;try{await api('/api/admin/users/'+button.dataset.id,'PATCH',{action:button.dataset.action});await Promise.all([loadUsers(),overview()]);}catch(e){error(e);button.disabled=false;}};
$('newAccount').onclick=()=>{$('accountForm').reset();$('accountError').hidden=true;$('accountDialog').showModal();};$('closeAccount').onclick=()=>$('accountDialog').close();$('accountDialog').addEventListener('close',()=>$('accountForm').reset());
$('accountForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;$('accountError').hidden=true;try{await api('/api/admin/users','POST',Object.fromEntries(new FormData(e.currentTarget)));$('accountDialog').close();page=1;await Promise.all([loadUsers(),overview()]);}catch(e){$('accountError').textContent=e.message;$('accountError').hidden=false;}finally{button.disabled=false;$('accountForm').elements.password.value='';}};
$('inviteForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const data=await api('/api/admin/invitations','POST',Object.fromEntries(new FormData(e.currentTarget)));$('newInviteCode').textContent=data.code;$('inviteResult').hidden=false;await loadInvites();}catch(e){error(e);}finally{button.disabled=false;}};
$('copyInvite').onclick=async()=>{try{await navigator.clipboard.writeText($('newInviteCode').textContent);$('copyInvite').textContent='已复制';}catch{error(new Error('请选中上方邀请码复制'));}};
$('invitesList').onclick=async e=>{const button=e.target.closest('[data-invite]');if(!button||button.disabled)return;button.disabled=true;try{await api('/api/admin/invitations/'+button.dataset.invite,'PATCH',{enabled:button.dataset.enabled==='true'});await loadInvites();}catch(e){error(e);button.disabled=false;}};
$('adminLogout').onclick=async()=>{try{await api('/api/logout','POST',{});location.replace('/login?admin=1');}catch(e){error(e);}};
try{const {user}=await api('/api/me');if(!user)location.replace('/login?admin=1');else if(user.role!=='admin')location.replace('/');else{$('adminName').textContent=user.name;await Promise.all([overview(),loadUsers()]);}}catch(e){error(e);}
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});

const tabs=[...document.querySelectorAll('[data-tab]')];tabs.forEach((button,index)=>{button.tabIndex=index===0?0:-1;button.addEventListener('keydown',event=>{const step=event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0;let next=step?(index+step+tabs.length)%tabs.length:event.key==='Home'?0:event.key==='End'?tabs.length-1:null;if(next===null)return;event.preventDefault();tabs[next].focus();tabs[next].click();});});
