import { useEffect, useState } from 'react'
import { LogoutControl } from './auth/SessionGate.jsx'
import { APP_VERSION } from '../version.js'
import { deletePlan, listPlans, updatePlan } from '../storage/localWorkspace.js'

function LineIcon({type}) {
 return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type==='history'?<><path d="M3 9a9 9 0 1 1 0 7M3 4v5h5M12 7v5l3 2"/></>:type==='lock'?<><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 15v2"/></>:type==='info'?<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>:<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>}</svg>
}
function Thumbnail({blob,name}) {
 const [url,setUrl]=useState('')
 useEffect(()=>{const value=URL.createObjectURL(blob);setUrl(value);return()=>URL.revokeObjectURL(value)},[blob])
 return <img src={url||undefined} alt={`${name}缩略图`}/>
}
export function ProductPages({page,setPage,displayName,onNameSave,onOpen,onDeleteActive,notify}) {
 const [records,setRecords]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(null),[recordName,setRecordName]=useState(''),[deleting,setDeleting]=useState(null),[busy,setBusy]=useState(false),[draft,setDraft]=useState(displayName),[profileError,setProfileError]=useState(''),[showPassword,setShowPassword]=useState(false)
 useEffect(()=>{setDraft(displayName);setProfileError('')},[displayName,page])
 useEffect(()=>{if(page!=='history')return;let live=true;setLoading(true);setError('');listPlans().then(rows=>{if(live)setRecords(rows)}).catch(()=>{if(live)setError('无法读取本机记录，请检查浏览器存储设置后重试。')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[page])
 async function refresh(){setRecords(await listPlans())}
 async function rename(e){e.preventDefault();const name=recordName.trim();if(!name||name.length>60){setError('记录名称需为 1–60 个字');return}setBusy(true);try{await updatePlan(editing,{name});await refresh();setEditing(null);setError('');notify('记录名称已保存')}catch{setError('重命名未保存，请重试')}finally{setBusy(false)}}
 async function remove(id){setBusy(true);try{await deletePlan(id);onDeleteActive(id);await refresh();setDeleting(null);setError('');notify('已删除这条本机记录，磁盘原图不受影响')}catch{setError('删除未完成，请重试')}finally{setBusy(false)}}
 async function saveName(e){e.preventDefault();const name=draft.trim();if(!name||name.length>24){setProfileError('请输入 1–24 个字的显示名称');return}try{onNameSave(name);setProfileError('');notify('显示名称已保存在当前设备')}catch{setProfileError('无法保存，请检查浏览器存储设置')}}
 const titles={history:'历史记录',account:'账户设置',profile:'个人资料',password:'修改密码',about:'关于软件'}
 return <main className={`product-page ${page==='history'?'history-page':''}`}>
 <button className="page-back" onClick={()=>setPage(['profile','password','about'].includes(page)?'account':'workspace')}><span>←</span>{['profile','password','about'].includes(page)?'账户设置':'返回工作台'}</button>
 <div className="product-title"><h2>{titles[page]}</h2>{page==='history'&&<span className="local-tag">本机记录</span>}</div>
 {page==='history'&&<>
 <p className="page-intro">保存在当前浏览器，可打开继续编辑。未启用云同步。</p>
 {loading?<div className="empty-records">正在读取记录…</div>:!records.length?<div className="empty-records"><LineIcon type="history"/><h3>还没有上传记录</h3><p>上传第一张户型图后，记录会保存在这里。</p><button className="quiet-primary" onClick={()=>setPage('workspace')}>返回工作台上传</button></div>:<div className="record-list">{records.map(r=><article className="record-row" key={r.id}><button className="record-thumbnail" aria-label={`打开记录 ${r.name}`} onClick={()=>onOpen(r)}><Thumbnail blob={r.blob} name={r.name}/></button><div className="record-body">{editing===r.id?<form onSubmit={rename} className="rename-form"><input aria-label="记录名称" autoFocus value={recordName} maxLength={60} onChange={e=>setRecordName(e.target.value)}/><button disabled={busy} type="submit">保存</button><button type="button" onClick={()=>setEditing(null)}>取消</button></form>:<button className="record-title" onClick={()=>onOpen(r)}>{r.name}</button>}<p>{new Date(r.createdAt).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})} 上传</p><span className="record-status">{r.points.length>=3?'轮廓已记录 · 分析待配置':r.angle!==0?'方位已调整':'待校准'}</span><div className="record-actions"><button onClick={()=>onOpen(r)}>打开记录</button><button onClick={()=>{setEditing(r.id);setRecordName(r.name);setDeleting(null)}}>重命名</button><button onClick={()=>{setDeleting(r.id);setEditing(null)}}>删除记录</button></div>{deleting===r.id&&<div className="delete-record-confirm"><p>删除此本机记录？磁盘原图和当前工作台图片不会被删除。</p><button disabled={busy} onClick={()=>remove(r.id)}>确认删除记录</button><button onClick={()=>setDeleting(null)}>取消</button></div>}</div></article>)}</div>}
 {error&&<p className="form-feedback error" role="alert">{error}</p>}
 </>}
 {page==='account'&&<><div className="account-identity"><span className="profile-monogram">{displayName?displayName.slice(0,1):<LineIcon/>}</span><div><h3>{displayName||'设备资料'}</h3><p>当前设备显示资料 · 本机测试账号已登录</p></div></div><div className="account-auth-entry"><LogoutControl/></div><div className="account-links">{[['profile','个人资料','修改此设备的显示名称','user'],['password','修改密码','改密服务接入后启用','lock'],['about','关于软件',`v${APP_VERSION} · 开发预览`,'info']].map(([target,title,sub,icon])=><button key={target} onClick={()=>setPage(target)}><LineIcon type={icon}/><span><strong>{title}</strong><small>{sub}</small></span><i>›</i></button>)}</div></>}
 {page==='profile'&&<form className="settings-form" onSubmit={saveName}><p className="page-intro">名称仅用于当前设备显示，不修改真实客户账户。</p><label htmlFor="display-name">显示名称</label><input id="display-name" value={draft} maxLength={24} placeholder="填写你希望显示的名字" autoComplete="off" onChange={e=>setDraft(e.target.value)}/><small>1–24 个字，保存在当前浏览器。</small>{profileError&&<p className="form-feedback error" role="alert">{profileError}</p>}<div className="form-actions"><button className="quiet-primary" type="submit">保存名称</button><button type="button" onClick={()=>setPage('account')}>取消</button></div>{displayName&&<button type="button" className="reset-profile" onClick={()=>{try{onNameSave('');setDraft('');notify('已恢复默认设备名称')}catch{setProfileError('无法保存，请重试')}}}>恢复默认名称</button>}</form>}
 {page==='password'&&<div className="settings-form"><div className="service-notice"><LineIcon type="lock"/><div><strong>改密服务未接入</strong><p>密码表单暂未启用。请勿输入真实密码；此预览不会读取、保存或提交密码。</p></div></div><form onSubmit={e=>e.preventDefault()}><fieldset disabled>{[['current-password','当前密码'],['new-password','新密码'],['confirm-password','确认新密码']].map(([id,label])=><div className="password-field" key={id}><label htmlFor={id}>{label}</label><input id={id} type={showPassword?'text':'password'} placeholder="接入改密服务后启用" autoComplete="off"/></div>)}</fieldset><button className="password-visibility" type="button" aria-pressed={showPassword} onClick={()=>setShowPassword(v=>!v)}>{showPassword?'隐藏密码':'显示密码'}<span>界面预览</span></button><small>启用后需验证当前密码；新密码至少 8 位，两次输入须一致。</small><div className="form-actions"><button className="quiet-primary" disabled type="submit">保存新密码</button><button type="button" onClick={()=>setPage('account')}>取消</button></div></form></div>}
 {page==='about'&&<div className="about-content"><div className="about-mark"><LineIcon type="info"/></div><h3>家居风水系统</h3><p className="about-version">v{APP_VERSION}<span>开发预览</span></p><dl><div><dt>记录保存</dt><dd>当前设备 · 当前浏览器</dd></div><div><dt>账户服务</dt><dd>本机登录已接入</dd></div><div><dt>分析规则</dt><dd>待配置</dd></div></dl><p className="page-intro">本机记录不等于云端备份。清除浏览器网站数据会移除本机记录。</p></div>}
 </main>
}
