export const recommendations = [
  {
    id: '01',
    sector: '北偏西',
    place: '入户玄关',
    short: '金山图',
    advice: '在入户玄关墙面放置金山图，形成进入住宅后的第一处布局重点。',
    schedule: '软装进场后完成',
    warning: '待确认：图样、尺寸与安装朝向',
    status: '待选图样',
    x: 28,
    y: 25,
  },
  {
    id: '02',
    sector: '中宫',
    place: '楼梯下方',
    short: '泰山石 · 水局',
    advice: '放置小型泰山石，并做小型水局',
    detail: '在楼梯下方放置一块小型泰山石，并结合地面完成水局布局。',
    schedule: '铺地施工前完成',
    warning: '待确认：水局尺寸与具体做法',
    status: '待定做法',
    x: 50,
    y: 52,
  },
  {
    id: '03',
    sector: '西北',
    place: '电梯与安全通道',
    short: '水局',
    advice: '在可施工范围内进行水局处理，公共区域部分需先确认权限。',
    schedule: '现场交底后实施',
    warning: '待确认：公共区域施工范围',
    status: '需确认范围',
    x: 27,
    y: 57,
  },
  {
    id: '04',
    sector: '东北',
    place: '楼梯安全区域',
    short: '土局',
    advice: '根据现场空间完成土局处理，材料和结构由老师进一步确认。',
    schedule: '装修施工阶段完成',
    warning: '待确认：土局材料与具体做法',
    status: '待定土局',
    x: 76,
    y: 65,
  },
  {
    id: '05',
    sector: '西南',
    place: '入户门',
    short: '99枚铜币布局',
    advice: '在入户门地面下方布置99枚黄铜五角硬币。',
    schedule: '地面封层前完成',
    warning: '待确认：排列方式与准确范围',
    status: '待定排列',
    x: 72,
    y: 28,
  },
]

export const checklistGroups = [
  {
    title: '铺地施工前',
    items: ['中宫楼梯下方 · 泰山石与水局', '西南入户门 · 99枚铜币布局'],
  },
  {
    title: '装修施工阶段',
    items: ['西北电梯区域 · 确认水局范围', '东北楼梯区域 · 确认土局做法'],
  },
  {
    title: '软装进场后',
    items: ['北偏西玄关 · 安装金山图'],
  },
]
